# -*- coding: utf-8 -*-
"""FlaskBackEnd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y5JydjEyl6pBAiAEQHDzOgDwZQAMs-pj
"""

from flask import *
from predict import predictImage
#import predict.py

app = Flask(__name__)


@app.route('/success', methods=['POST'])
def success():
    if request.method == 'POST':
        f = request.files['file']
    return predictImage(f)


if __name__ == '__main__':
    app.debug = True
    app.run('0.0.0.0')
